# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Privat/EDS/Projects/Labor/Labor4/Labor4.srcs/sources_1/ip/blk_mem_gen_ROM/blk_mem_gen_ROM.xci
# IP: The module: 'blk_mem_gen_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Privat/EDS/Projects/Labor/Labor4/Labor4.gen/sources_1/ip/blk_mem_gen_ROM/blk_mem_gen_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_ROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Privat/EDS/Projects/Labor/Labor4/Labor4.srcs/sources_1/ip/blk_mem_gen_ROM/blk_mem_gen_ROM.xci
# IP: The module: 'blk_mem_gen_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Privat/EDS/Projects/Labor/Labor4/Labor4.gen/sources_1/ip/blk_mem_gen_ROM/blk_mem_gen_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
